title: Dan Lapone
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Dan Lapone"
job: "Cloud & Systems Engineering"

address: Orange County, California
email: uncommon@danlapone.com
linkedin_username: danlapone

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag